# Generated by Django 5.1 on 2024-08-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English')], default=('math', 'Math'), max_length=50),
        ),
    ]
