# Generated by Django 5.1 on 2024-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_jobpost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English')], default='Math', max_length=50),
        ),
    ]
