# Generated by Django 5.1 on 2024-09-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_jobpost_subject'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile'),
        ),
    ]
